apiVersion: v1
kind: Service
metadata:
  name: pwa-be-service
spec:
  type: NodePort
  selector:
    app: pwa-be
  ports:
    - port: 5000       # Puerto del servicio dentro del cluster
      targetPort: 5000 # Puerto del contenedor
      nodePort: 30007  # Puerto expuesto en tu PC (puede ser cualquiera entre 30000-32767)
